version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: VIP
    environment:
      MYSQL_DATABASE: 'test_database'
      MYSQL_USER: 'suscribete'
      MYSQL_PASSWORD: 'Recuerda_Suscribirte'
      MYSQL_ROOT_PASSWORD: 'D_aleLike'
